# Generated by Django 3.1.2 on 2020-10-25 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_news_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='newssubcat',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AlterField(
            model_name='news',
            name='catname',
            field=models.CharField(default='-', max_length=20),
        ),
    ]
