# Generated by Django 3.1.2 on 2020-10-25 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20201025_2147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='newssubcat',
            new_name='subcatname',
        ),
    ]
